# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Notes' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Notes
  pod 'RxSwift', '6.5.0'
  pod 'RxCocoa', '6.5.0'
  pod 'RxDataSources', '~> 5.0'
  pod 'RxRealm'

  target 'NotesTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'NotesUITests' do
    # Pods for testing
  end
end
